### ISSUE TITLE
module build error

### ISSUE THREAD

**Issue by hamdiwanis** [HNeukermans/ng2-signalr#101]
i get this error trying to serve the project locally

```
ERROR in ./node_modules/ng2-signalr/index.ts
Module build failed: Error: /project/node_modules/ng2-signalr/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (project/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:653:23)
    at plugin.done.then (/project/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 14:20-42
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```
im using angular 5 and pbriones version.

**Comment by hamdiwanis** [comment]
It look likes it moved to a _dist repository, thanks

**Comment by penleychan** [comment]
@hamdiwanis How did you resolve this? I am experiencing the same issue. I don't see _dist folder under ng2-signalr.

Regards

**Comment by hamdiwanis** [comment]
Hello, until the latest version that supports angular 5 is pushed to npm, they use a temp fork here
`npm install pbriones/ng2-signalr-dist`
Good luck.
