### ISSUE TITLE
 Signalr.connect should allow configuration override 

### ISSUE THREAD

**Issue by HNeukermans** [HNeukermans/ng2-signalr#19]
Current there is only 1 place configure singalr. = during module configuration.
This makes dynamic configuration impossible.

Solution: 
Signalr.connect() (without parameter) should start a connection using the default configuration found in the module.
Overriding default configuration should be supported using the Signalr.connect(config SignalRConfiguration), passing in all default configuration overrides.

I propose to make all properties of  SignalRConfiguration optional.

**Comment by shaulbehr** [comment]
I tried, but I don't have rights to your repo :-)

**Comment by HNeukermans** [comment]
Hey,

nice of you willing to contribute.
A common approach  is to fork the repo, then make the change to your local repo, then do a pull request to my repo

**Comment by HNeukermans** [comment]
this feature was added in v1.0.7

**Comment by shaulbehr** [comment]
Thank you!
I'm used to using GitFlow, so I'm not familiar with the concept of forking.  For future reference, how do I make a pull request if I can't push my code to a branch of your repo?

**Comment by shaulbehr** [comment]
Hi,
Got latest version, now I'm getting a runtime error as soon as I try to connect:

> EXCEPTION: Uncaught (in promise): Error: Signalr failed to initialize. Script 'jquery.js' is missing. Please make sure to include jquery script.
Error: Signalr failed to initialize. Script 'jquery.js' is missing. Please make sure to include jquery script.
    at getJquery (http://localhost:4200/vendor.bundle.js:120936:15) [angular]
    at getJConnectionFn (http://localhost:4200/vendor.bundle.js:120927:18) [angular]
    at createSignalr (http://localhost:4200/vendor.bundle.js:120922:25) [angular]
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:874:61) [angular]
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:879:129) [angular]
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:1228:63) [angular]
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:70344:44) [angular]
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4200/vendor.bundle.js:108613:45) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4200/vendor.bundle.js:109041:49) [angular]
    at ElementInjector.get (http://localhost:4200/vendor.bundle.js:108117:27) [angular]
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor.bundle.js:107874:24) [angular]
    at ReflectiveInjector_._getByKey (http://localhost:4200/vendor.bundle.js:107809:25) [angular]
    at ReflectiveInjector_.get (http://localhost:4200/vendor.bundle.js:107678:21) [angular]
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4200/vendor.bundle.js:108613:45) [angular]

In my `packages.json` file I have under "dependencies":
```
    "jquery": "^3.1.1",
```
What am I doing wrong?

**Comment by HNeukermans** [comment]
You can use your chrome debugger and set a breakpoint @http://localhost:4200/vendor.bundle.js:120936:15. See if window.JQuery is present. If, it is not there, that explains the error. Otherwise it is a bug. Let me know

**Comment by shaulbehr** [comment]
Hm, `window.jQuery` is *not* present.  What does that mean, considering that jQuery is explicitly listed in `package.json`?

**Comment by HNeukermans** [comment]
You need to import jquery before importing ng2-signalr to get rid of the error. Check the webpack installation setup.

**Comment by shaulbehr** [comment]
Yep.  FYI, I don't have a `vendor.ts file; I inserted those lines in `angular-cli.json`.  Now I'm past those errors, thanks!

**Comment by HNeukermans** [comment]
thx for letting me know. Did you also reference the signalr.jquery script inside angular-cli.json?

**Comment by shaulbehr** [comment]
yes

**Comment by marcoippel** [comment]
Can you tell me how you fixed it i tried to add it also directly to the angular-cli.json but still jquery isn't loaded.

**Comment by DaveMonag** [comment]
`      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/signalr/jquery.signalR.js"
      ],
`
Find scripts in your angular-cli.json, and add those two lines. Make sure you've got jquery and signalr listed in your package.json.
