### ISSUE TITLE
Module build failed: Error

### ISSUE THREAD

**Issue by atulmish** [HNeukermans/ng2-signalr#62]
ERROR in ./~/ng2-signalr/index.ts
Module build failed: Error
    at new FatalError (**\node_modules\tslint\lib\error.js:31:23)
    at Function.findConfiguration (**\node_modules\tslint\lib\configuration.js:56:15)
    at parseConfigFile (**\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (**\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (**\node_modules\tslint-loader\index.js:139:17)
 @ ./src/app/core/notification/notification.module.ts 10:20-42 11:20-42

**Comment by DaveMonag** [comment]
We're going to need context here. You can't just post a vague error and hope it gets fixed from that alone.

**Comment by atulmish** [comment]
I was unable to compile the application and getting that vague error. I think that was my machine specific issue. So closing it.
