### ISSUE TITLE
Exception: Uncaught (in promise): Error: DI Error

### ISSUE THREAD

**Issue by nadircan** [HNeukermans/ng2-signalr#74]
I ran angular-cli example with signalr. Now I want to add my project. I created notification.component.ts.

```
import { Component, ViewChild, OnInit } from '@angular/core';
import { SignalR, IConnectionOptions } from "ng2-signalr";


@Component({
  selector: 'notification',
  templateUrl: './notification.component.html'
})
export class NotificationComponent{



  constructor(private _signalR: SignalR) {
  }
//here's the error.

   connect() {
      let o: IConnectionOptions;
      let conx = this._signalR.createConnection();
      conx.status.subscribe((s) => console.warn(s.name));
      conx.start().then((c) => {
  
        console.log("c",c)
  
        let listener = c.listenFor('Hello');
        listener.subscribe(() => {
                console.log('received hello');
              //this.notification.show();
            
  
        });
         c.invoke('SayHello').then(() => {
            console.log("invoke oldu");
          });
      });
    }
  
     connect2() {
      let o: IConnectionOptions;
      let conx = this._signalR.connect().then((c) => {
  
        let listener = c.listenFor('shortTask.status');
        listener.subscribe(() => {
                console.log('received hello');
  
  
        });
        c.invoke('SayHello').then(() => {
  
        });
      });
    }
 
}

```

I created notification.module.ts

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgaModule } from '../../theme/nga.module';
import { NgsModule } from '../../shared/ngs.module';
import { routing } from './login.routing';
import { NotificationComponent } from "./notification.component";
import { SignalRModule, SignalRConfiguration, SignalR } from "ng2-signalr";

export function createConfig(): SignalRConfiguration {
  const c = new SignalRConfiguration();
  c.hubName = 'EventHub';
  //c.qs = { ChannelName: 'tasks' };
  c.url = 'http://s-kgdev:94';
  c.logging = true;
  return c;
}

@NgModule({
    imports: [
        CommonModule,
        ReactiveFormsModule,
        FormsModule,
        NgaModule,
        NgsModule,
     SignalRModule.forRoot(createConfig)
        
    ],
    declarations: [
       NotificationComponent
    ]})
export default class NotificationModule { }

```

Error.

```
EXCEPTION: Uncaught (in promise): Error: DI Error
Error: DI Error
    at NoProviderError.ZoneAwareError (http://localhost:3000/polyfills.dll.js:4948:33)
    at NoProviderError.BaseError [as constructor] (http://localhost:3000/vendor.dll.js:28670:16)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:3000/vendor.dll.js:58039:16)
    at new NoProviderError (http://localhost:3000/vendor.dll.js:58101:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:3000/vendor.dll.js:79008:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:3000/vendor.dll.js:79047:25)
    at ReflectiveInjector_._getByKey (http://localhost:3000/vendor.dll.js:78979:25)
    at ReflectiveInjector_.get (http://localhost:3000/vendor.dll.js:78848:21)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:3000/vendor.dll.js:58993:52)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:3000/vendor.dll.js:79789:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:3000/vendor.dll.js:80217:49)
    at ElementInjector.get (http://localhost:3000/vendor.dll.js:79290:27)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:3000/vendor.dll.js:79044:24)
    at ReflectiveInjector_._getByKey (http://localhost:3000/vendor.dll.js:78979:25)
    at ReflectiveInjector_.get (http://localhost:3000/vendor.dll.js:78848:21)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:3000/vendor.dll.js:79789:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:3000/vendor.dll.js:80217:49)
    at ElementInjector.get (http://localhost:3000/vendor.dll.js:79290:27)
    at HubsModuleInjector.NgModuleInjector.get (http://localhost:3000/vendor.dll.js:58993:52)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:3000/vendor.dll.js:79044:24)
    at ReflectiveInjector_._getByKey (http://localhost:3000/vendor.dll.js:78979:25)
    at ReflectiveInjector_.get (http://localhost:3000/vendor.dll.js:78848:21)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:3000/vendor.dll.js:79789:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:3000/vendor.dll.js:80217:49)
    at ElementInjector.get (http://localhost:3000/vendor.dll.js:79290:27)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:3000/vendor.dll.js:79044:24)
    at ReflectiveInjector_._getByKey (http://localhost:3000/vendor.dll.js:78979:25)
    at ReflectiveInjector_.get (http://localhost:3000/vendor.dll.js:78848:21)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:3000/vendor.dll.js:79789:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:3000/vendor.dll.js:80217:49)
    at CompiledTemplate.proxyViewClass.View_NotificationComponent_Host0.createInternal (/HubsModule/NotificationComponent/host.ngfactory.js:15:81)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:3000/vendor.dll.js:79745:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:3000/vendor.dll.js:80201:52)
    at ComponentFactory.create (http://localhost:3000/vendor.dll.js:42440:25)
    at ViewContainerRef_.createComponent (http://localhost:3000/vendor.dll.js:59461:62)
    at RouterOutlet.activate (http://localhost:3000/vendor.dll.js:65281:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:3000/vendor.dll.js:23734:16)
    at ActivateRoutes.activateRoutes (http://localhost:3000/vendor.dll.js:23701:26)
    at http://localhost:3000/vendor.dll.js:23637:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:3000/vendor.dll.js:23637:29)
    at ActivateRoutes.activateRoutes (http://localhost:3000/vendor.dll.js:23702:26)
    at http://localhost:3000/vendor.dll.js:23637:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:3000/vendor.dll.js:23637:29)
    at ActivateRoutes.activateRoutes (http://localhost:3000/vendor.dll.js:23707:22)
    at http://localhost:3000/vendor.dll.js:23637:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:3000/vendor.dll.js:23637:29)
    at ActivateRoutes.activateRoutes (http://localhost:3000/vendor.dll.js:23702:26)
    at http://localhost:3000/vendor.dll.js:23637:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:3000/vendor.dll.js:23637:29)
    at ActivateRoutes.activate (http://localhost:3000/vendor.dll.js:23611:14)
    at http://localhost:3000/vendor.dll.js:23179:22
    at SafeSubscriber._next (http://localhost:3000/vendor.dll.js:167:25)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3000/vendor.dll.js:612:16)
    at SafeSubscriber.next (http://localhost:3000/vendor.dll.js:561:22)
    at Subscriber._next (http://localhost:3000/vendor.dll.js:503:26)
    at Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:15599:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at ReduceSubscriber._complete (http://localhost:3000/vendor.dll.js:33978:30)
    at ReduceSubscriber.Subscriber.complete (http://localhost:3000/vendor.dll.js:492:18)
    at MergeMapSubscriber._complete (http://localhost:3000/vendor.dll.js:15591:30)
    at MergeMapSubscriber.Subscriber.complete (http://localhost:3000/vendor.dll.js:492:18)
    at ArrayObservable._subscribe (http://localhost:3000/vendor.dll.js:8526:24)
    at ArrayObservable.Observable._trySubscribe (http://localhost:3000/vendor.dll.js:131:25)
    at ArrayObservable.Observable.subscribe (http://localhost:3000/vendor.dll.js:119:27)
    at MergeMapOperator.call (http://localhost:3000/vendor.dll.js:15541:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at ReduceOperator.call (http://localhost:3000/vendor.dll.js:33933:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at MapOperator.call (http://localhost:3000/vendor.dll.js:12127:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at Object.subscribeToResult (http://localhost:3000/vendor.dll.js:702:27)
    at MergeMapSubscriber._innerSub (http://localhost:3000/vendor.dll.js:15586:38)
    at MergeMapSubscriber._tryNext (http://localhost:3000/vendor.dll.js:15583:14)
    at MergeMapSubscriber._next (http://localhost:3000/vendor.dll.js:15566:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:15599:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at EverySubscriber.notifyComplete (http://localhost:3000/vendor.dll.js:47534:26)
    at EverySubscriber._complete (http://localhost:3000/vendor.dll.js:47551:14)
    at EverySubscriber.Subscriber.complete (http://localhost:3000/vendor.dll.js:492:18)
    at MergeMapSubscriber._complete (http://localhost:3000/vendor.dll.js:15591:30)
    at MergeMapSubscriber.Subscriber.complete (http://localhost:3000/vendor.dll.js:492:18)
    at ArrayObservable._subscribe (http://localhost:3000/vendor.dll.js:8526:24)
    at ArrayObservable.Observable._trySubscribe (http://localhost:3000/vendor.dll.js:131:25)
    at ArrayObservable.Observable.subscribe (http://localhost:3000/vendor.dll.js:119:27)
    at MergeMapOperator.call (http://localhost:3000/vendor.dll.js:15541:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at EveryOperator.call (http://localhost:3000/vendor.dll.js:47514:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at MapOperator.call (http://localhost:3000/vendor.dll.js:12127:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at Object.subscribeToResult (http://localhost:3000/vendor.dll.js:702:27)
    at MergeMapSubscriber._innerSub (http://localhost:3000/vendor.dll.js:15586:38)
    at MergeMapSubscriber._tryNext (http://localhost:3000/vendor.dll.js:15583:14)
    at MergeMapSubscriber._next (http://localhost:3000/vendor.dll.js:15566:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:15599:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at ScalarObservable._subscribe (http://localhost:3000/vendor.dll.js:46912:24)
    at ScalarObservable.Observable._trySubscribe (http://localhost:3000/vendor.dll.js:131:25)
    at ScalarObservable.Observable.subscribe (http://localhost:3000/vendor.dll.js:119:27)
    at MapOperator.call (http://localhost:3000/vendor.dll.js:12127:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at Object.subscribeToResult (http://localhost:3000/vendor.dll.js:702:27)
    at MergeMapSubscriber._innerSub (http://localhost:3000/vendor.dll.js:15586:38)
    at MergeMapSubscriber._tryNext (http://localhost:3000/vendor.dll.js:15583:14)
    at MergeMapSubscriber._next (http://localhost:3000/vendor.dll.js:15566:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.dll.js:503:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at LastSubscriber._complete (http://localhost:3000/vendor.dll.js:67232:25)
    at LastSubscriber.Subscriber.complete (http://localhost:3000/vendor.dll.js:492:18)
    at MergeAllSubscriber.notifyComplete (http://localhost:3000/vendor.dll.js:15444:30)
    at InnerSubscriber._complete (http://localhost:3000/vendor.dll.js:85557:21)
    at InnerSubscriber.Subscriber.complete (http://localhost:3000/vendor.dll.js:492:18)
    at MapSubscriber.Subscriber._complete (http://localhost:3000/vendor.dll.js:510:26)
    at MapSubscriber.Subscriber.complete (http://localhost:3000/vendor.dll.js:492:18)
    at CatchSubscriber.Subscriber._complete (http://localhost:3000/vendor.dll.js:510:26)
    at CatchSubscriber.Subscriber.complete (http://localhost:3000/vendor.dll.js:492:18)
    at FirstSubscriber._emitFinal (http://localhost:3000/vendor.dll.js:47796:25)
    at FirstSubscriber._emit (http://localhost:3000/vendor.dll.js:47778:14)
    at FirstSubscriber._tryPredicate (http://localhost:3000/vendor.dll.js:47770:18)
    at FirstSubscriber._next (http://localhost:3000/vendor.dll.js:47754:18)
    at FirstSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:663:26)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.dll.js:503:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:15599:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.dll.js:503:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at FirstSubscriber._emitFinal (http://localhost:3000/vendor.dll.js:47795:25)
    at FirstSubscriber._emit (http://localhost:3000/vendor.dll.js:47778:14)
    at FirstSubscriber._tryPredicate (http://localhost:3000/vendor.dll.js:47770:18)
    at FirstSubscriber._next (http://localhost:3000/vendor.dll.js:47754:18)
    at FirstSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:663:26)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.dll.js:503:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:15599:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.dll.js:503:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at FirstSubscriber._emitFinal (http://localhost:3000/vendor.dll.js:47795:25)
    at FirstSubscriber._emit (http://localhost:3000/vendor.dll.js:47778:14)
    at FirstSubscriber._tryPredicate (http://localhost:3000/vendor.dll.js:47770:18)
    at FirstSubscriber._next (http://localhost:3000/vendor.dll.js:47754:18)
    at FirstSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:663:26)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.dll.js:503:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:15599:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.dll.js:503:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at FirstSubscriber._emitFinal (http://localhost:3000/vendor.dll.js:47795:25)
    at FirstSubscriber._emit (http://localhost:3000/vendor.dll.js:47778:14)
    at FirstSubscriber._tryPredicate (http://localhost:3000/vendor.dll.js:47770:18)
    at FirstSubscriber._next (http://localhost:3000/vendor.dll.js:47754:18)
    at FirstSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:663:26)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.dll.js:503:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:15599:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at Object.subscribeToResult (http://localhost:3000/vendor.dll.js:697:25)
    at MergeMapSubscriber._innerSub (http://localhost:3000/vendor.dll.js:15586:38)
    at MergeMapSubscriber._tryNext (http://localhost:3000/vendor.dll.js:15583:14)
    at MergeMapSubscriber._next (http://localhost:3000/vendor.dll.js:15566:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at ScalarObservable._subscribe (http://localhost:3000/vendor.dll.js:46912:24)
    at ScalarObservable.Observable._trySubscribe (http://localhost:3000/vendor.dll.js:131:25)
    at ScalarObservable.Observable.subscribe (http://localhost:3000/vendor.dll.js:119:27)
    at MergeMapOperator.call (http://localhost:3000/vendor.dll.js:15541:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at CatchOperator.call (http://localhost:3000/vendor.dll.js:47006:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at Object.subscribeToResult (http://localhost:3000/vendor.dll.js:702:27)
    at MergeAllSubscriber._next (http://localhost:3000/vendor.dll.js:15424:42)
    at MergeAllSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at ArrayObservable._subscribe (http://localhost:3000/vendor.dll.js:8524:28)
    at ArrayObservable.Observable._trySubscribe (http://localhost:3000/vendor.dll.js:131:25)
    at ArrayObservable.Observable.subscribe (http://localhost:3000/vendor.dll.js:119:27)
    at MapOperator.call (http://localhost:3000/vendor.dll.js:12127:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at MergeAllOperator.call (http://localhost:3000/vendor.dll.js:15402:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at FirstOperator.call (http://localhost:3000/vendor.dll.js:47730:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at CatchOperator.call (http://localhost:3000/vendor.dll.js:47006:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at MapOperator.call (http://localhost:3000/vendor.dll.js:12127:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at Object.subscribeToResult (http://localhost:3000/vendor.dll.js:702:27)
    at MergeMapSubscriber._innerSub (http://localhost:3000/vendor.dll.js:15586:38)
    at MergeMapSubscriber._tryNext (http://localhost:3000/vendor.dll.js:15583:14)
    at MergeMapSubscriber._next (http://localhost:3000/vendor.dll.js:15566:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at ScalarObservable._subscribe (http://localhost:3000/vendor.dll.js:46912:24)
    at ScalarObservable.Observable._trySubscribe (http://localhost:3000/vendor.dll.js:131:25)
    at ScalarObservable.Observable.subscribe (http://localhost:3000/vendor.dll.js:119:27)
    at MergeMapOperator.call (http://localhost:3000/vendor.dll.js:15541:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at CatchOperator.call (http://localhost:3000/vendor.dll.js:47006:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at Object.subscribeToResult (http://localhost:3000/vendor.dll.js:702:27)
    at MergeAllSubscriber._next (http://localhost:3000/vendor.dll.js:15424:42)
    at MergeAllSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at ScalarObservable._subscribe (http://localhost:3000/vendor.dll.js:46912:24)
    at ScalarObservable.Observable._trySubscribe (http://localhost:3000/vendor.dll.js:131:25)
    at ScalarObservable.Observable.subscribe (http://localhost:3000/vendor.dll.js:119:27)
    at MapOperator.call (http://localhost:3000/vendor.dll.js:12127:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at MergeAllOperator.call (http://localhost:3000/vendor.dll.js:15402:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at FirstOperator.call (http://localhost:3000/vendor.dll.js:47730:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at CatchOperator.call (http://localhost:3000/vendor.dll.js:47006:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at MapOperator.call (http://localhost:3000/vendor.dll.js:12127:23)
    at Observable.subscribe (http://localhost:3000/vendor.dll.js:116:22)
    at Object.subscribeToResult (http://localhost:3000/vendor.dll.js:702:27)
    at MergeMapSubscriber._innerSub (http://localhost:3000/vendor.dll.js:15586:38)
    at MergeMapSubscriber._tryNext (http://localhost:3000/vendor.dll.js:15583:14)
    at MergeMapSubscriber._next (http://localhost:3000/vendor.dll.js:15566:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:15599:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MapSubscriber._next (http://localhost:3000/vendor.dll.js:12156:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.dll.js:15599:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.dll.js:85550:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.dll.js:467:18)
    at http://localhost:3000/vendor.dll.js:66426:36
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.dll.js:4320:26)
    at Object.onInvoke (http://localhost:3000/vendor.dll.js:30337:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.dll.js:4319:32)
    at Zone.run (http://localhost:3000/polyfills.dll.js:4116:43)
    at http://localhost:3000/polyfills.dll.js:4669:57
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.dll.js:4353:31)
    at Object.onInvokeTask (http://localhost:3000/vendor.dll.js:30328:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.dll.js:4352:36)
    at Zone.runTask (http://localhost:3000/polyfills.dll.js:4156:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.dll.js:4519:35)




```

Where is my mistake?

**Comment by nadircan** [comment]
My project uses webpack. So I have modified vendor.ts and the issue was resolved.
