### ISSUE TITLE
Cannot read property 'forRoot' of undefined

### ISSUE THREAD

**Issue by Nielsie89** [HNeukermans/ng2-signalr#85]
Hello,

I tried to copy the code in the example of the chatservice but its not working for me. Im getting the following error:

`Error: (SystemJS) Cannot read property 'forRoot' of undefined
	TypeError: Cannot read property 'forRoot' of undefined
	    at Object.eval (http://localhost:15133/scripts/modules/app.module.js:108:40)
	    at eval (http://localhost:15133/scripts/modules/app.module.js:200:4)
	    at eval (http://localhost:15133/scripts/modules/app.module.js:201:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:15133/scripts/modules/app.module.js
	Evaluating http://localhost:15133/scripts/main.js
	Error loading http://localhost:15133/scripts/main.js
	    at Object.eval (http://localhost:15133/scripts/modules/app.module.js:108:40)
	    at eval (http://localhost:15133/scripts/modules/app.module.js:200:4)
	    at eval (http://localhost:15133/scripts/modules/app.module.js:201:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:15133/scripts/modules/app.module.js
	Evaluating http://localhost:15133/scripts/main.js
	Error loading http://localhost:15133/scripts/main.js`

**My app.module.ts:**

`...
import { SignalRModule } from 'ng2-signalr';
import { SignalRConfiguration } from 'ng2-signalr';

export function createConfig(): SignalRConfiguration {
    const c = new SignalRConfiguration();
    c.hubName = 'Ng2SignalRHub';
    c.qs = { user: 'donald' };
    c.url = 'http://ng2-signalr-backend.azurewebsites.net/';
    c.logging = true;
    return c;
}

@NgModule({
    imports:
    [
        SignalRModule.forRoot(createConfig),
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        HttpModule,
        DataTableModule,
        routing,
    ],
...

providers: [
...
ConnectionResolver,
        { provide: LOCALE_ID, useValue: 'nl-NL' }
    ],
    bootstrap:    [ AppComponent ]
`
**System.config.js**

`
(function(global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': '/node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': '/scripts/',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

            // other libraries
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            'rxjs': 'npm:rxjs',
            'primeng': 'npm:primeng',
            'moment': 'npm:moment/min/moment.min.js',
            'ng2-signalr': 'npm:signalr/jquery.signalR.js'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            },
            primeng: {
                defaultExtension: 'js'
            }
        }
    });
})(this);`

**route.resolver.ts:**

`import { Resolve } from '@angular/router';
import { SignalR, SignalRConnection } from 'ng2-signalr';
import { Injectable } from '@angular/core';

@Injectable()
export class ConnectionResolver implements Resolve<SignalRConnection> {

    constructor(private _signalR: SignalR) { }

    resolve() {
        console.log('ConnectionResolver. Resolving...');
        return this._signalR.connect();
    }
}`

Sorry for the styling of the question, im a bit of a noob on the site. Could anyone tell me what Im doing wrong?

**Comment by Nielsie89** [comment]
Facepalm -_- 

System.config.js
'ng2-signalr': 'npm:signalr/jquery.signalR.js' -> 'ng2-signalr': 'npm:ng2-signalr'
