### ISSUE TITLE
Angular Universal Server Side Rendering Window Issue

### ISSUE THREAD

**Issue by cbhatt** [HNeukermans/ng2-signalr#89]
Hello,

I needed to upgrade my application to Angular Universal and after that signalR is not working. I know 'window' object is not available on server side so for code using 'window' object we need to check isPlatformBrowser. But regarding signalR, we need to configure this in module imports. So when we call SignalRModule.forRoot(initSignalRConfig) in module imports, it breaks due to 'window' object. 
I tried to import this in module constructor and in component as well, but it didn't work.

On further google, i found other packages which integrates signalR with Asp.Net core. But that will needs lots of changes and i am not sure about Asp.Net core issues later. So i want to avoid Asp.Net core approach.

Is there any way to use this library with Angular Universal ?

Thanks

**Comment by Chembeti** [comment]
To make SEO compatible, I also need my app to support Angular Universal but blocked. I am getting below error (with ng2-signalr v5.0.0):
```

import { SignalRConfiguration } from "./signalr.configuration";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.w9yb....
```
Any help is highly appreciated.

**Comment by Chembeti** [comment]
I got past above problem by using webpack for bundling and compiling. However, when I run the application, I am getting below error:
`ReferenceError: window is not defined`

Above error hits at below function:

```
function getJquery() {
    var /** @type {?} */ jQuery = (/** @type {?} */ (window)).jQuery;
    if (jQuery == null) {
        throw new Error('Signalr failed to initialize. Script \'jquery.js\' is missing. Please make sure to include jquery script.');
    }
    return jQuery;
}

```
I have tried putting isPlatformBrowser checks while initializing SignalR; however problem still persists.
